// Code generated by protoc-gen-go. DO NOT EDIT.
// source: smartenergytable-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_7be9bf9d675643a6, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type GameObject struct {
	RoomId               *RoomId  `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PosX                 float32  `protobuf:"fixed32,3,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY                 float32  `protobuf:"fixed32,4,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	PosZ                 float32  `protobuf:"fixed32,5,opt,name=pos_z,json=posZ,proto3" json:"pos_z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameObject) Reset()         { *m = GameObject{} }
func (m *GameObject) String() string { return proto.CompactTextString(m) }
func (*GameObject) ProtoMessage()    {}
func (*GameObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_7be9bf9d675643a6, []int{1}
}

func (m *GameObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameObject.Unmarshal(m, b)
}
func (m *GameObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameObject.Marshal(b, m, deterministic)
}
func (m *GameObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameObject.Merge(m, src)
}
func (m *GameObject) XXX_Size() int {
	return xxx_messageInfo_GameObject.Size(m)
}
func (m *GameObject) XXX_DiscardUnknown() {
	xxx_messageInfo_GameObject.DiscardUnknown(m)
}

var xxx_messageInfo_GameObject proto.InternalMessageInfo

func (m *GameObject) GetRoomId() *RoomId {
	if m != nil {
		return m.RoomId
	}
	return nil
}

func (m *GameObject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GameObject) GetPosX() float32 {
	if m != nil {
		return m.PosX
	}
	return 0
}

func (m *GameObject) GetPosY() float32 {
	if m != nil {
		return m.PosY
	}
	return 0
}

func (m *GameObject) GetPosZ() float32 {
	if m != nil {
		return m.PosZ
	}
	return 0
}

type Room struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Objects              []*GameObject `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	SceneId              int32         `protobuf:"varint,3,opt,name=sceneId,proto3" json:"sceneId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_7be9bf9d675643a6, []int{2}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Room) GetObjects() []*GameObject {
	if m != nil {
		return m.Objects
	}
	return nil
}

func (m *Room) GetSceneId() int32 {
	if m != nil {
		return m.SceneId
	}
	return 0
}

type RoomId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomId) Reset()         { *m = RoomId{} }
func (m *RoomId) String() string { return proto.CompactTextString(m) }
func (*RoomId) ProtoMessage()    {}
func (*RoomId) Descriptor() ([]byte, []int) {
	return fileDescriptor_7be9bf9d675643a6, []int{3}
}

func (m *RoomId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomId.Unmarshal(m, b)
}
func (m *RoomId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomId.Marshal(b, m, deterministic)
}
func (m *RoomId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomId.Merge(m, src)
}
func (m *RoomId) XXX_Size() int {
	return xxx_messageInfo_RoomId.Size(m)
}
func (m *RoomId) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomId.DiscardUnknown(m)
}

var xxx_messageInfo_RoomId proto.InternalMessageInfo

func (m *RoomId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RoomId) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Scene struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SceneId              int32    `protobuf:"varint,2,opt,name=sceneId,proto3" json:"sceneId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scene) Reset()         { *m = Scene{} }
func (m *Scene) String() string { return proto.CompactTextString(m) }
func (*Scene) ProtoMessage()    {}
func (*Scene) Descriptor() ([]byte, []int) {
	return fileDescriptor_7be9bf9d675643a6, []int{4}
}

func (m *Scene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scene.Unmarshal(m, b)
}
func (m *Scene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scene.Marshal(b, m, deterministic)
}
func (m *Scene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scene.Merge(m, src)
}
func (m *Scene) XXX_Size() int {
	return xxx_messageInfo_Scene.Size(m)
}
func (m *Scene) XXX_DiscardUnknown() {
	xxx_messageInfo_Scene.DiscardUnknown(m)
}

var xxx_messageInfo_Scene proto.InternalMessageInfo

func (m *Scene) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Scene) GetSceneId() int32 {
	if m != nil {
		return m.SceneId
	}
	return 0
}

type Update struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Room                 *Room    `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_7be9bf9d675643a6, []int{5}
}

func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (m *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(m, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

func (m *Update) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Update) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*GameObject)(nil), "GameObject")
	proto.RegisterType((*Room)(nil), "Room")
	proto.RegisterType((*RoomId)(nil), "RoomId")
	proto.RegisterType((*Scene)(nil), "Scene")
	proto.RegisterType((*Update)(nil), "Update")
}

func init() { proto.RegisterFile("smartenergytable-service.proto", fileDescriptor_7be9bf9d675643a6) }

var fileDescriptor_7be9bf9d675643a6 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x4d, 0x6f, 0x9b, 0x40,
	0x10, 0x35, 0x98, 0x8f, 0x7a, 0x68, 0xab, 0x6a, 0x7b, 0x30, 0xb5, 0x54, 0x17, 0x21, 0xb9, 0xe2,
	0x52, 0x5c, 0xe3, 0x5f, 0xd0, 0x5a, 0x56, 0xe5, 0xaa, 0x52, 0xa5, 0x75, 0xa2, 0x24, 0xbe, 0x58,
	0x6b, 0x33, 0x72, 0x48, 0x02, 0x8b, 0x16, 0x82, 0xe2, 0xdc, 0xf2, 0x77, 0xf3, 0x2b, 0x22, 0x16,
	0x83, 0xb1, 0x7c, 0x5a, 0x76, 0x66, 0xde, 0xbc, 0xb7, 0xef, 0x01, 0xc3, 0x2c, 0x66, 0x22, 0xc7,
	0x04, 0xc5, 0x6e, 0x9f, 0xb3, 0xcd, 0x03, 0xfe, 0xc8, 0x50, 0x14, 0xd1, 0x16, 0xfd, 0x54, 0xf0,
	0x9c, 0xbb, 0x26, 0xe8, 0xf3, 0x38, 0xcd, 0xf7, 0xee, 0x8b, 0x02, 0xf0, 0x87, 0xc5, 0xf8, 0x7f,
	0x73, 0x87, 0xdb, 0x9c, 0x38, 0x60, 0x0a, 0xce, 0xe3, 0x75, 0x14, 0xda, 0x8a, 0xa3, 0x78, 0x56,
	0x60, 0xfa, 0x94, 0xf3, 0x78, 0x11, 0x52, 0x43, 0xc8, 0x93, 0x10, 0xd0, 0x12, 0x16, 0xa3, 0xad,
	0x3a, 0x8a, 0xd7, 0xa3, 0xf2, 0x9b, 0x7c, 0x06, 0x3d, 0xe5, 0xd9, 0xfa, 0xc9, 0xee, 0x3a, 0x8a,
	0xa7, 0x52, 0x2d, 0xe5, 0xd9, 0x75, 0x5d, 0xdc, 0xdb, 0x5a, 0x53, 0xbc, 0xa9, 0x8b, 0xcf, 0xb6,
	0xde, 0x14, 0x57, 0xee, 0x15, 0x68, 0x25, 0x09, 0xf9, 0x08, 0xea, 0x81, 0xb7, 0x47, 0xd5, 0x28,
	0x24, 0x23, 0x30, 0xb9, 0x94, 0x95, 0xd9, 0xaa, 0xd3, 0xf5, 0xac, 0xc0, 0xf2, 0x8f, 0x52, 0x69,
	0xdd, 0x23, 0x36, 0x98, 0xd9, 0x16, 0x13, 0x5c, 0x84, 0x92, 0x5f, 0xa7, 0xf5, 0xd5, 0x9d, 0x80,
	0x51, 0xa9, 0x3f, 0x5b, 0xdd, 0x07, 0xf3, 0x31, 0x43, 0x51, 0xbe, 0xb3, 0x7a, 0x88, 0x51, 0x5e,
	0x25, 0x44, 0x5f, 0x96, 0xe8, 0x33, 0x44, 0x8b, 0x45, 0x3d, 0x65, 0x99, 0x82, 0x71, 0x99, 0x86,
	0x2c, 0x3f, 0xc7, 0x7c, 0x01, 0xad, 0x74, 0x4d, 0x02, 0xac, 0x40, 0x97, 0x56, 0x52, 0x59, 0x0a,
	0x5e, 0x15, 0xe8, 0x2f, 0xcb, 0x8c, 0xe6, 0x32, 0xa3, 0x8b, 0x32, 0xa3, 0x65, 0x15, 0x11, 0xf9,
	0x0a, 0x30, 0x13, 0xc8, 0x72, 0x94, 0xae, 0x18, 0xbe, 0x4c, 0x6a, 0x50, 0xc1, 0xdd, 0x0e, 0x71,
	0xe0, 0xdd, 0x5f, 0x1e, 0x25, 0xb2, 0x59, 0xc7, 0x33, 0x30, 0xfd, 0x4a, 0x83, 0xdb, 0xf9, 0xa9,
	0x90, 0xef, 0xf0, 0xe1, 0x57, 0x18, 0xb6, 0x62, 0x6d, 0x1b, 0x37, 0x38, 0x2c, 0x74, 0x3b, 0x64,
	0x04, 0x9f, 0x28, 0xc6, 0xbc, 0xc0, 0xd6, 0x68, 0xb3, 0xf1, 0x38, 0xf6, 0x0d, 0xac, 0xd9, 0x2d,
	0x4b, 0x76, 0x58, 0x39, 0x63, 0xf8, 0xf2, 0x6c, 0x0d, 0x0c, 0xa1, 0xf7, 0x0f, 0x59, 0x81, 0xa7,
	0x92, 0x9a, 0xfe, 0xef, 0xf7, 0x2b, 0x48, 0xef, 0x77, 0x63, 0x96, 0x46, 0xe3, 0x62, 0xb2, 0x31,
	0xe4, 0x2f, 0x38, 0x7d, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x00, 0x9f, 0x35, 0x89, 0xa4, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SmartEnergyTableServiceClient is the client API for SmartEnergyTableService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SmartEnergyTableServiceClient interface {
	CreateRoom(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Room, error)
	JoinRoom(ctx context.Context, in *RoomId, opts ...grpc.CallOption) (SmartEnergyTableService_JoinRoomClient, error)
	AddGameObject(ctx context.Context, in *GameObject, opts ...grpc.CallOption) (*Empty, error)
	RemoveGameObject(ctx context.Context, in *RoomId, opts ...grpc.CallOption) (*Empty, error)
	ChangeScene(ctx context.Context, in *Scene, opts ...grpc.CallOption) (*Empty, error)
	LeaveRoom(ctx context.Context, in *RoomId, opts ...grpc.CallOption) (*Empty, error)
}

type smartEnergyTableServiceClient struct {
	cc *grpc.ClientConn
}

func NewSmartEnergyTableServiceClient(cc *grpc.ClientConn) SmartEnergyTableServiceClient {
	return &smartEnergyTableServiceClient{cc}
}

func (c *smartEnergyTableServiceClient) CreateRoom(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/SmartEnergyTableService/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartEnergyTableServiceClient) JoinRoom(ctx context.Context, in *RoomId, opts ...grpc.CallOption) (SmartEnergyTableService_JoinRoomClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SmartEnergyTableService_serviceDesc.Streams[0], "/SmartEnergyTableService/JoinRoom", opts...)
	if err != nil {
		return nil, err
	}
	x := &smartEnergyTableServiceJoinRoomClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SmartEnergyTableService_JoinRoomClient interface {
	Recv() (*Update, error)
	grpc.ClientStream
}

type smartEnergyTableServiceJoinRoomClient struct {
	grpc.ClientStream
}

func (x *smartEnergyTableServiceJoinRoomClient) Recv() (*Update, error) {
	m := new(Update)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *smartEnergyTableServiceClient) AddGameObject(ctx context.Context, in *GameObject, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/SmartEnergyTableService/AddGameObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartEnergyTableServiceClient) RemoveGameObject(ctx context.Context, in *RoomId, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/SmartEnergyTableService/RemoveGameObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartEnergyTableServiceClient) ChangeScene(ctx context.Context, in *Scene, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/SmartEnergyTableService/ChangeScene", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartEnergyTableServiceClient) LeaveRoom(ctx context.Context, in *RoomId, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/SmartEnergyTableService/LeaveRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmartEnergyTableServiceServer is the server API for SmartEnergyTableService service.
type SmartEnergyTableServiceServer interface {
	CreateRoom(context.Context, *Empty) (*Room, error)
	JoinRoom(*RoomId, SmartEnergyTableService_JoinRoomServer) error
	AddGameObject(context.Context, *GameObject) (*Empty, error)
	RemoveGameObject(context.Context, *RoomId) (*Empty, error)
	ChangeScene(context.Context, *Scene) (*Empty, error)
	LeaveRoom(context.Context, *RoomId) (*Empty, error)
}

// UnimplementedSmartEnergyTableServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSmartEnergyTableServiceServer struct {
}

func (*UnimplementedSmartEnergyTableServiceServer) CreateRoom(ctx context.Context, req *Empty) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (*UnimplementedSmartEnergyTableServiceServer) JoinRoom(req *RoomId, srv SmartEnergyTableService_JoinRoomServer) error {
	return status.Errorf(codes.Unimplemented, "method JoinRoom not implemented")
}
func (*UnimplementedSmartEnergyTableServiceServer) AddGameObject(ctx context.Context, req *GameObject) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGameObject not implemented")
}
func (*UnimplementedSmartEnergyTableServiceServer) RemoveGameObject(ctx context.Context, req *RoomId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveGameObject not implemented")
}
func (*UnimplementedSmartEnergyTableServiceServer) ChangeScene(ctx context.Context, req *Scene) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeScene not implemented")
}
func (*UnimplementedSmartEnergyTableServiceServer) LeaveRoom(ctx context.Context, req *RoomId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveRoom not implemented")
}

func RegisterSmartEnergyTableServiceServer(s *grpc.Server, srv SmartEnergyTableServiceServer) {
	s.RegisterService(&_SmartEnergyTableService_serviceDesc, srv)
}

func _SmartEnergyTableService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartEnergyTableServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SmartEnergyTableService/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartEnergyTableServiceServer).CreateRoom(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartEnergyTableService_JoinRoom_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RoomId)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SmartEnergyTableServiceServer).JoinRoom(m, &smartEnergyTableServiceJoinRoomServer{stream})
}

type SmartEnergyTableService_JoinRoomServer interface {
	Send(*Update) error
	grpc.ServerStream
}

type smartEnergyTableServiceJoinRoomServer struct {
	grpc.ServerStream
}

func (x *smartEnergyTableServiceJoinRoomServer) Send(m *Update) error {
	return x.ServerStream.SendMsg(m)
}

func _SmartEnergyTableService_AddGameObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartEnergyTableServiceServer).AddGameObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SmartEnergyTableService/AddGameObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartEnergyTableServiceServer).AddGameObject(ctx, req.(*GameObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartEnergyTableService_RemoveGameObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartEnergyTableServiceServer).RemoveGameObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SmartEnergyTableService/RemoveGameObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartEnergyTableServiceServer).RemoveGameObject(ctx, req.(*RoomId))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartEnergyTableService_ChangeScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Scene)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartEnergyTableServiceServer).ChangeScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SmartEnergyTableService/ChangeScene",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartEnergyTableServiceServer).ChangeScene(ctx, req.(*Scene))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartEnergyTableService_LeaveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartEnergyTableServiceServer).LeaveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SmartEnergyTableService/LeaveRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartEnergyTableServiceServer).LeaveRoom(ctx, req.(*RoomId))
	}
	return interceptor(ctx, in, info, handler)
}

var _SmartEnergyTableService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SmartEnergyTableService",
	HandlerType: (*SmartEnergyTableServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _SmartEnergyTableService_CreateRoom_Handler,
		},
		{
			MethodName: "AddGameObject",
			Handler:    _SmartEnergyTableService_AddGameObject_Handler,
		},
		{
			MethodName: "RemoveGameObject",
			Handler:    _SmartEnergyTableService_RemoveGameObject_Handler,
		},
		{
			MethodName: "ChangeScene",
			Handler:    _SmartEnergyTableService_ChangeScene_Handler,
		},
		{
			MethodName: "LeaveRoom",
			Handler:    _SmartEnergyTableService_LeaveRoom_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "JoinRoom",
			Handler:       _SmartEnergyTableService_JoinRoom_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "smartenergytable-service.proto",
}
